Roads/Controllers/MachineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Roads.Models;

namespace Roads.Controllers
{
    [OutputCache(Duration = 100)]
    public class MachineController : Controller
    {
        // GET: Machine
        Models.RoadsEntities1 obj = new Models.RoadsEntities1();
        Models.ViewModel obj2 = new Models.ViewModel();
        Models.TransVM tvm = new Models.TransVM();

        public ActionResult Index()
        {
            obj2.listMach = obj.tblMaches.ToList();

            var owner = obj.tblOwners.ToList();
            ViewBag.owners = new SelectList(owner, "Owner_Num", "Owner_Name");

            return View(obj2);
        }

        [HttpPost]
        public ActionResult Insert(Models.tblMach machine)
        {
            obj.tblMaches.Add(machine);
            obj.SaveChanges();
            
            return RedirectToAction("Index");
        }

        public ActionResult Logout()
        {
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(Models.ViewModel machine)
        {
            Models.tblMach old = new Models.tblMach();

            old.Mach_No = (int)machine.Mach_No;
            old.Mach_Desc = machine.Mach_Desc;
            old.Lease_Rate = machine.Lease_Rate;
            var name = obj.tblOwners.Where(m => m.Owner_Name == machine.Owner_Name).FirstOrDefault();
            old.Owner_Num = name.Owner_Num;
            old.Active = machine.Active;

            obj.Entry(old).State = EntityState.Modified;
            obj.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Index2() //// gridview get
        {
            //Models.RoadViewModel rvm = new Models.RoadViewModel();
            //Models.RoadsEntities obj = new Models.RoadsEntities();
            obj2.listRoad = obj.tblRoads.ToList();

            List<Models.tblType> items = obj.tblTypes.ToList();
            ViewBag.sel = new SelectList(items, "Type_Id", "Type_Desc");

            return View(obj2);
        }

        [HttpPost]
        public ActionResult Index3(Models.tblRoad r)
        {   ////insert
            //Models.RoadViewModel rvm = new Models.RoadViewModel();
            //Models.RoadsEntities obj = new Models.RoadsEntities();
            //Models.tblRoad tblr = new Models.tblRoad();
            //tblr.BIA_No =Convert.ToInt32(r.BIA_No);
            //tblr.Road_Name = r.Road_Name;
            //tblr.Type_Id = r.Type_Id;
            //tblr.Miles = r.Miles;

            obj.tblRoads.Add(r);
            obj.SaveChanges();
            return RedirectToAction("Index2");
        }

        [HttpPost]
        public ActionResult Edit2(Models.ViewModel r)
        {
            //Models.RoadsEntities obj = new Models.RoadsEntities();
            Models.tblRoad tblr = new Models.tblRoad();

            tblr.BIA_No = Convert.ToInt32(r.BIA_No);
            tblr.Road_Name = r.Road_Name;
            tblr.Type_Id = r.Type_Id;
            tblr.Miles = r.Miles;

            obj.Entry(tblr).State = EntityState.Modified;
            obj.SaveChanges();
            return RedirectToAction("Index2");
        }

        public ActionResult Trans()
        {
            List<SelectListItem> list1 = new List<SelectListItem>();
            List<SelectListItem> list2 = new List<SelectListItem>();
            List<SelectListItem> list3 = new List<SelectListItem>();
            List<SelectListItem> list4 = new List<SelectListItem>();

            foreach (Models.tblEmp a in obj.tblEmps)
            {
                list1.Add(new SelectListItem()
                {
                    Text = a.Emp_Name,
                    Value = a.Emp_no.ToString()
                });
            }

            foreach(Models.tblMach a in obj.tblMaches)
            {
                list2.Add(new SelectListItem()
                {
                    Text = a.Mach_Desc,
                    Value = a.Mach_No.ToString()
                });
            }

            foreach(Models.tblRoad a in obj.tblRoads)
            {
                list3.Add(new SelectListItem()
                {
                    Text = a.Road_Name,
                    Value = a.BIA_No.ToString()
                });
            }

            foreach(Models.tblAct a in obj.tblActs)
            {
                list4.Add(new SelectListItem()
                {
                    Text = a.Activity_Desc,
                    Value = a.Activity_Code.ToString()
                });
            }

            tvm.Emp_List = list1;
            tvm.Mach_List = list2;
            tvm.BIA_List = list3;
            tvm.Activity_List = list4;

            return View(tvm);
        }

        public ActionResult Create_Trans(Models.tblTransaction trans)
        {
            obj.tblTransactions.Add(trans);
            obj.SaveChanges();

            return RedirectToAction("Trans");
        }


        public ActionResult Kendo()
        {
            return View();
        }

        public ActionResult tblTransactions_Read([DataSourceRequest]DataSourceRequest request)
        {
            IQueryable<tblTransaction> tbltransactions = obj.tblTransactions;
            DataSourceResult result = tbltransactions.ToDataSourceResult(request, tblTransaction => new {
                //AutoNumber = tblTransaction.AutoNumber,
                //Trans_Date = tblTransaction.Trans_Date,
                Emp_No = tblTransaction.Emp_No,
                Mach_No = tblTransaction.Mach_No,
                BIA_No = tblTransaction.BIA_No,
                Activity_Code = tblTransaction.Activity_Code,
                Hours = tblTransaction.Hours,
                Lease_Chg = tblTransaction.Lease_Chg,
            });

            return Json(result);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult tblTransactions_Update([DataSourceRequest]DataSourceRequest request, tblTransaction tblTransaction)
        {
            if (ModelState.IsValid)
            {
                var entity = new tblTransaction
                {
                    //AutoNumber = tblTransaction.AutoNumber,
                    //Trans_Date = tblTransaction.Trans_Date,
                    Emp_No = tblTransaction.Emp_No,
                    Mach_No = tblTransaction.Mach_No,
                    BIA_No = tblTransaction.BIA_No,
                    Activity_Code = tblTransaction.Activity_Code,
                    Hours = tblTransaction.Hours,
                    Lease_Chg = tblTransaction.Lease_Chg,
                };

                obj.tblTransactions.Attach(entity);
                obj.Entry(entity).State = EntityState.Modified;
                obj.SaveChanges();
            }

            return Json(new[] { tblTransaction }.ToDataSourceResult(request, ModelState));
        }

        protected override void Dispose(bool disposing)
        {
            obj.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult tblEmp_Read([DataSourceRequest]DataSourceRequest request)
        {
            IQueryable<tblEmp> tblEmps = obj.tblEmps;
            DataSourceResult result = tblEmps.ToDataSourceResult(request, tblEmp => new {
                Emp_Name = tblEmp.Emp_Name,
                Emp_No = tblEmp.Emp_no
            });

            return Json(result);
        }

        public ActionResult tblMach_Read([DataSourceRequest]DataSourceRequest request)
        {
            IQueryable<tblMach> tblMachs = obj.tblMaches;
            DataSourceResult result = tblMachs.ToDataSourceResult(request, tblMach => new {
                Mach_Desc = tblMach.Mach_Desc,
                Mach_No = tblMach.Mach_No
            });

            return Json(result);
        }

        public ActionResult tblRoad_Read([DataSourceRequest]DataSourceRequest request)
        {
            IQueryable<tblRoad> tblRoads = obj.tblRoads;
            DataSourceResult result = tblRoads.ToDataSourceResult(request, tblRoad => new {
                Road_Name = tblRoad.Road_Name,
                BIA_No = tblRoad.BIA_No
            });

            return Json(result);
        }

        public ActionResult tblAct_Read([DataSourceRequest]DataSourceRequest request)
        {
            IQueryable<tblAct> tblActs = obj.tblActs;
            DataSourceResult result = tblActs.ToDataSourceResult(request, tblAct => new {
                Activity_Desc = tblAct.Activity_Desc,
                Activity_Code = tblAct.Activity_Code
            });

            return Json(result);
        }
    }
}

Roads/Views/Machine/Index.cshtml
@model Roads.Models.ViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "List of Machines";
    WebGrid grid = new WebGrid(Model.listMach, canSort: false);
}

<script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

<style type="text/css">
    .webgrid-table {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        font-size: 1.2em;
        width: 100%;
        display: table;
        border-collapse: separate;
        border: solid 1px #98BF21;
        background-color: white;
    }

        .webgrid-table td, th {
            border: 1px solid #98BF21;
            padding: 3px 7px 2px;
        }

    .webgrid-header {
        background-color: #A7C942;
        color: #FFFFFF;
        padding-bottom: 4px;
        padding-top: 5px;
        text-align: left;
    }

    .webgrid-footer {
    }

    .webgrid-row-style {
        padding: 3px 7px 2px;
    }

    .webgrid-alternating-row {
        background-color: #EAF2D3;
        padding: 3px 7px 2px;
    }
</style>


<script>
    $(function(){
        $("#dialog").dialog({
            autoOpen: false,
            modal: true,
            title: "Edit",
            show: {
                effect: "explode",
                duration: 1000
            },
            hide: {
                effect: "explode",
                duration: 1000
            },
            buttons: {
                'OK': function () {
                    var new_machine = $("#mach").val();
                    var new_machine_desc = $("#desc").val();
                    var new_rate = $("#r8").val();
                    var old_owner_name = $("#oname").val();
                    var new_active = $("#aktive").prop("checked");

                    var machine = {
                        "Mach_No" : new_machine,
                        "Mach_Desc" : new_machine_desc,
                        "Lease_Rate" : new_rate,
                        "Owner_Name" : old_owner_name,
                        "Active" : new_active
                    };

                    $.ajax({
                        type: "POST",
                        data: machine,
                        url: "/Machine/Edit"
                    });
                    setTimeout (function(){
                        location.reload();
                    }, 100)
                    $(this).dialog('close');
                },
                'Close': function () {
                    $(this).dialog('close');
                }
            }
        });
    })
    function ShowDialog(id) {
        var row = $("#" + id).closest('tr');
        $("#mach").val(row.children()[0].innerHTML);
        $("#desc").val(row.children()[1].innerHTML);
        $("#r8").val(row.children()[2].innerHTML);
        $("#oname").val(row.children()[3].innerHTML);
        if (row.children()[4].children[0].checked) {
            $("#aktive").val(1);
            $("#aktive").prop("checked", true);
        }
        else {
            $("#aktive").val(0);
            $("#aktive").prop("checked", false);
        }
        $("#dialog").dialog('open');
    }
</script>

@using (Html.BeginForm("Insert", "Machine")) 
{
    @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        @*<h4>tblMach</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Mach_No, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mach_No, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mach_No, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.Mach_Desc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mach_Desc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mach_Desc, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.Lease_Rate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lease_Rate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lease_Rate, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.Owner_Num, "Owner_Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.Owner_Num, (IEnumerable<SelectListItem>)ViewBag.owners, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Owner_Num, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @grid.GetHtml(
    tableStyle: "webgrid-table",
    headerStyle: "webgrid-header",
    footerStyle: "webgrid-footer",
    alternatingRowStyle: "webgrid-alternating-row",
    rowStyle: "webgrid-row-style",
    columns: grid.Columns(
        grid.Column("Mach_No", "Mach_No"),
        grid.Column("Mach_Desc", "Mach_Desc"),
        grid.Column("Lease_Rate", "Lease_Rate"),
        grid.Column("tblOwner.Owner_Name", "Owner_Name"),
        grid.Column("Active", format:@<text><input type="checkbox" @(item.Active ? "checked='checked'" : "") disabled="disabled" /></text>),
        grid.Column("Edit", "", @<text><input type="button" id="@item.Mach_No" onclick="ShowDialog(@item.Mach_No)" value="Edit" /></text>)
        ))
</div>

<div id="dialog">
    <input type="text" id="mach" disabled="disabled" />
    <input type="text" id="desc" placeholder="Description" />
    <input type="text" id="r8" placeholder="Rate" />
    <input type="hidden" id="oname" />
    <br />
    <label>Active</label>
    <input type="checkbox" id="aktive" />
</div>

Roads/Views/Machine/Index2.cshtml
@model Roads.Models.ViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var grid = new WebGrid(source: Model.listRoad, canSort: false);
}

<script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

<style type="text/css">
    .webgrid-table {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        font-size: 1.2em;
        width: 100%;
        display: table;
        border-collapse: separate;
        border: solid 1px #98BF21;
        background-color: white;
    }

        .webgrid-table td, th {
            border: 1px solid #98BF21;
            padding: 3px 7px 2px;
        }

    .webgrid-header {
        background-color: #A7C942;
        color: #FFFFFF;
        padding-bottom: 4px;
        padding-top: 5px;
        text-align: left;
    }

    .webgrid-footer {
    }

    .webgrid-row-style {
        padding: 3px 7px 2px;
    }

    .webgrid-alternating-row {
        background-color: #EAF2D3;
        padding: 3px 7px 2px;
    }
</style>


    @*<img src="http://www.summitworks.com/assets/images/SummitLogoFontVector.jpg" />*@
    @*insert*@
    @using (Html.BeginForm("Index3", "Machine"))
    {
        @Html.AntiForgeryToken()
        <div>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <table>
                <tr>
                    <td>
                        @Html.TextBoxFor(model => model.BIA_No, "", new { @placeholder = "Road number" })
                        @Html.ValidationMessageFor(model => model.BIA_No, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.TextBoxFor(model => model.Road_Name, "", new { @placeholder = "Road name" })
                        @Html.ValidationMessageFor(model => model.Road_Name, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.TextBoxFor(model => model.Miles, "", new { @placeholder = "Miles" })
                        @Html.ValidationMessageFor(model => model.Miles, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DropDownListFor(m => m.Type_Id, (IEnumerable<SelectListItem>)ViewBag.sel, "Select road type")
                        @Html.ValidationMessageFor(model => model.Type_Id, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td>
                        <br />
                    </td>
                </tr>
                <tr>
                    <td>
                        <input type="submit" value="Create" />
                    </td>
                </tr>
            </table>
        </div>
    }
    <div>
        @{
            @grid.GetHtml(
            tableStyle: "webgrid-table",
            headerStyle: "webgrid-header",
            footerStyle: "webgrid-footer",
            alternatingRowStyle: "webgrid-alternating-row",
            rowStyle: "webgrid-row-style",
            columns: grid.Columns(
                grid.Column("BIA_No", "Road code", @<input type="text" id="code_@item.BIA_No" readonly value="@item.BIA_No">),
                grid.Column("Road_Name", "Road name", @<input type="text" id="name_@item.BIA_No" readonly value="@item.Road_Name">),
                grid.Column("Type_Id", "Road type", @<input type="text" id="type_@item.BIA_No" readonly value="@item.Type_Id">),
                grid.Column("Miles", "Miles", @<input type="text" id="mile_@item.BIA_No" readonly value="@item.Miles">),
                grid.Column("", "", @<text><input type="button" value="Edit" onclick="pup(@item.BIA_No)"> </text>)
            )
        )
        }
    </div>

    @*<div id="dialog" title="EDIT">
            <table>
                <tr>
                    <td>Code</td>
                    <td>
                        <input type="text" />
                    </td>
                </tr>
                <tr>
                    <td>Name</td>
                    <td>
                        <input type="text" />
                    </td>
                </tr>
                <tr>
                    <td>Miles</td>
                    <td>
                        <input type="text" />
                    </td>
                </tr>
            </table>
            <select>
                <option>Type I</option>
                <option>Type II</option>
                <option>Type III</option>
            </select>
            <br />
            <button>Save</button>
        </div>*@

    <div id="dialog">
        @using (Html.BeginForm("Edit2", "Machine"))
        {
            @Html.AntiForgeryToken()
            <div>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                @Html.TextBoxFor(model => model.BIA_No, "", new { @placeholder = "Road number", @id = "code" })
                @Html.ValidationMessageFor(model => model.BIA_No, "", new { @class = "text-danger" })
                <br />
                @Html.TextBoxFor(model => model.Road_Name, "", new { @placeholder = "Road name", @id = "name" })
                @Html.ValidationMessageFor(model => model.Road_Name, "", new { @class = "text-danger" })
                <br />
                @Html.DropDownListFor(m => m.Type_Id, (IEnumerable<SelectListItem>)ViewBag.sel, new { @id = "type" })
                @Html.ValidationMessageFor(model => model.Type_Id, "", new { @class = "text-danger" })
                <br />
                @Html.TextBoxFor(model => model.Miles, "", new { @placeholder = "Miles", @id = "mile" })
                @Html.ValidationMessageFor(model => model.Miles, "", new { @class = "text-danger" })
                <br />
                <input type="submit" value="Save" />
            </div>
        }
    </div>
    <script>
        $("#dialog").dialog({
            autoOpen: false,
            modal: true,
            title: "Edit",
            show: {
                effect: "explode",
                duration: 1000
            },
            hide: {
                effect: "explode",
                duration: 1000
            }
        })
        function pup(code) {
            var id1 = "code_" + code;
            var id2 = "name_" + code;
            var id3 = "type_" + code;
            var id4 = "mile_" + code;

            var v1 = document.getElementById(id1).value;
            var v2 = document.getElementById(id2).value;
            var v3 = document.getElementById(id3).value;
            var v4 = document.getElementById(id4).value;

            document.getElementById("code").value = v1;
            document.getElementById("name").value = v2;
            document.getElementById("type").value = v3;
            document.getElementById("mile").value = v4;

            $("#dialog").dialog("open");
        }
    </script>

Roads/Views/Machine/List.cshtml
//Controller
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MTERoads.Controllers
{
    public class MachineController : Controller
    {
        // GET: Machine
        public ActionResult Machines(string MachineCode, string MachineDescription, string LeaseRate, string Owner_Num)
        {
            Models.RoadsEntities1 owner = new Models.RoadsEntities1();
            List<SelectListItem>
    list = new List<SelectListItem>
        ();
        foreach (Models.tblOwner a in owner.tblOwners)
        {
        list.Add(new SelectListItem()
        {
        Text = a.Owner_Name,
        Value = a.Owner_Num.ToString()
        });
        }

        ViewBag.Owners = list;
        return View();
        }
        [HttpPost]
        public ActionResult Insert(Models.tblMach m)
        {
        Models.RoadsEntities1 obj = new Models.RoadsEntities1();
        obj.tblMaches.Add(m);
        obj.SaveChanges();
        return RedirectToAction("Machines");
        }
        public ActionResult Machines2()
        {
        //var users = new List<Models.tblMach>
            ();

            using (Models.RoadsEntities1 dc = new Models.RoadsEntities1())
            {
            List<Models.tblMach>
                users = dc.tblMaches.ToList();
                return View(users);
                }

                }
                public ActionResult Edit()
                {
                return RedirectToAction("Machines2");
                }
                }
                }
                //End Controller

                //Machine Insert
                @model MTERoads.Models.tblMach
                @{
                    Layout = "~/Views/Shared/_Layout.cshtml";
                }

                <!DOCTYPE html>

                <html>
                <head>
                    <meta name="viewport" content="width=device-width" />
                    <title>Machines</title>
                    <style>
                        #input {
                            position: fixed;
                            left: 10%;
                            width: 80%;
                        }

                        #AddMachine {
                            background-color: #006400;
                            color: #ffffff;
                        }
                    </style>
                </head>
                <body>

                    @using (Html.BeginForm("Insert", "Machine"))
                    {
                        <br />
                        <fieldset id="input">
                            <br />
                            @Html.TextBoxFor(m => m.Mach_No, new { type = "text", placeholder = "Machine Code", required = "required" })
                            @Html.TextBoxFor(m => m.Mach_Desc, new { type = "text", placeholder = "Machine Name", required = "required" })
                            <input id="AddMachine" type="submit" value="Add New Machine" />
                            <br /><br />
                            @Html.TextBoxFor(m => m.Lease_Rate, new { type = "text", placeholder = "Lease Rate", required = "required" })
                            @Html.DropDownListFor(m => m.Owner_Num, (IEnumerable<SelectListItem>)ViewBag.Owners, "--Select Owner--")
                            <br />
                        </fieldset>
                    }
                </body>
            </html>
            //End Machine Insert

            //Machine Table
            @model IEnumerable<MTERoads.Models.tblMach>

            @{
                Layout = null;
            }

            <!DOCTYPE html>

            <html>
            <head>
                <meta name="viewport" content="width=device-width" />
                <title>Machines2</title>
                <style>
                    .MachineGrid {
                        width: 100%;
                    }

                    .GridRow {
                        background-color: #f0f0f0;
                    }

                    .GridAltRow {
                        background-color: #ffffff;
                    }

                    .GridHeader {
                        background-color: #f0f0f0;
                        color: #000000;
                    }

                    a[type="btnType"] {
                        background-color: #006400;
                        border: 1px solid #787878;
                        cursor: pointer;
                        font-size: 1.2em;
                        font-weight: 600;
                        padding: 7px;
                        margin-right: 8px;
                        width: auto;
                        text-decoration: none;
                    }

                    .HeaderBar {
                        background-color: #006400;
                        width: 100%;
                        height: 30px;
                        align-content: center;
                    }

                    .RoadHeader {
                        color: #ffffff;
                        font-size: 20px;
                    }
                </style>
                <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
                <script src="//code.jquery.com/jquery-1.10.2.js"></script>
                <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
                <script>
        $(document).ready(function () {
            $('.show').click(function () {
                $('#dialog-form-edit').dialog('open');
            });

            $('#dialog-form-edit').dialog({
                autoOpen: false,
                modal: true,
                height: 350,
                width: 400,
            });
        });
                </script>
            </head>
            <body>
                <div class="HeaderBar">
                    <h1 class="RoadHeader">&nbsp;&nbsp;Roads</h1>
                </div>
                <script type="text/javascript">
        function show(No, Desc, Rate, Owner, Active) {
            $('#edit-Mach_No').val(No);
            $('#edit-Mach_Desc').val(Desc);
            $('#edit-Lease_Rate').val(Rate);
            $('#edit-Owner_Num').val(Owner);
            if (Active == 'onclick') {
                $('#edit-Active').attr("checked", "checked");
            } else {
                $('#edit-Active').attr("checked", null);
            }
            $('#dialog-form-edit').dialog('open');
        }
                </script>
                @{
                    WebGrid grid = new WebGrid(source: Model);
                    @grid.GetHtml(tableStyle: "MachineGrid", headerStyle: "GridHeader", rowStyle: "GridRow", alternatingRowStyle: "GridAltRow", columns: new[] {
    grid.Column("Mach_No", "Machine Number"),
    grid.Column("Mach_Desc", "Machine Description"),
    grid.Column("Lease_Rate", "Lease Rate"),
    grid.Column("Owner_Num", "Owner Number"),
    grid.Column(header: "Active", format: @<text><input name="Active"
                                                        type="checkbox" value="@item.Active" checked=@(item.Active == true ? "Checked" : null) /></text>),
    grid.Column("", format: @<text><button type="button" id="edit" onclick="show('@item.Mach_No', '@item.Mach_Desc', '@item.Lease_Rate', '@item.Owner_Num', '@item.Active')">Edit</button></text>) })
                }
                <div id="dialog-form-edit" title="Edit Book">
                    <label id="lblMachNo">Machine Number: </label>
                    <br />
                    <input type="text" id="edit-Mach_No" disabled="disabled" name="Mach_No" />
                    <br />
                    <label id="lblMachDesc">Machine Name:</label>
                    <br />
                    <input type="text" id="edit-Mach_Desc" placeholder="Machine Description" />
                    <br />
                    <label id="lblLease_Rate">Lease Rate: </label>
                    <br />
                    <input type="text" id="edit-Lease_Rate" placeholder="Lease Rate" />
                    <br />
                    <label id="lblOwnerNum">Owner Number: </label>
                    <br />
                    <input type="text" id="edit-Owner_Num" placeholder="Owner Number" />
                    <br />
                    <label id="lblActive">Active</label>
                    <input type="checkbox" id="edit-Active" />
                    <br /><br />
                    @Html.ActionLink("Save", "Edit", "Machine", new { Type = "btnType" })
                </div>
            </body>
        </html>
        //End Machine Table